apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  labels:
    kubernetes.courselabs.co: container-security
spec:
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      # automountServiceAccountToken: false
      # securityContext:
      #  runAsUser: 65534
      #  runAsGroup: 3000
      containers:
        - name: app
          image: sixeyed/whoami:21.04
          env:
            - name: WHOAMI_MODE
              value: q
          ports:
            - containerPort: 80
              name: http
          # resources:
          #  limits:
          #    cpu: 125m
          #    memory: 50M
          # securityContext:          
          #  readOnlyRootFilesystem: true
          #  allowPrivilegeEscalation: false
          #  capabilities:
          #    drop:
          #      - all