version: "3.7"

services:

  gogs:
    image: courselabs/gogs:0.12.3
    ports:
      - "3000:3000"

  jenkins:
    image: courselabs/jenkins:2.319.1
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
